# Generated by Django 5.1.3 on 2025-04-30 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('users', '0004_alter_user_email_alter_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic'),
        ),
    ]
