# Generated by Django 5.1.3 on 2025-05-28 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateAndTime', models.DateTimeField()),
                ('Additional_notes', models.TextField(blank=True, null=True)),
                ('Visit_summary', models.TextField(blank=True, null=True)),
                ('Prescriptions', models.TextField(blank=True, null=True)),
                ('Analysis_diagnosis', models.TextField(blank=True, null=True)),
                ('analysis', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='analysis.analysis')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='analysis.report')),
            ],
        ),
    ]
