# Generated by Django 5.1.3 on 2025-06-16 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_remove_analysis_visit_alter_report_analysis_and_more'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit', to='analysis.analysis'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_report', to='analysis.report'),
        ),
    ]
