# Generated by Django 5.1.3 on 2025-06-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='enable_ai_diagnosis',
            field=models.BooleanField(default=False),
        ),
    ]
