# Generated by Django 5.1.3 on 2025-06-26 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visit_enable_ai_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='enable_ai_diagnosis',
        ),
    ]
