# Generated by Django 5.1.3 on 2025-06-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_alter_visit_analysis_alter_visit_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='patient',
        ),
    ]
