# Generated by Django 5.1.3 on 2025-06-23 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='analysis_results/Images/')),
                ('Analysis_type', models.CharField(choices=[('Steiner', 'Steiner')], max_length=7)),
                ('Result', models.JSONField(blank=True, null=True)),
                ('steiner_report', models.FileField(blank=True, max_length=255, null=True, upload_to='analysis_results/Steiner_Reports/')),
                ('steiner_image', models.FileField(blank=True, max_length=255, null=True, upload_to='analysis_results/Steiner_Images/')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='analysis.analysis')),
            ],
        ),
    ]
