# Generated by Django 5.1.3 on 2025-06-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='analysis_images/')),
                ('Analysis_type', models.CharField(choices=[('Steiner', 'Steiner'), ('Downs', 'Downs'), ('Bjork', 'Bjork'), ('Wits', 'Wits')], max_length=7)),
                ('Result', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
        ),
    ]
