# Generated by Django 5.1.3 on 2025-06-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='analysis_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
