# Generated by Django 5.1.3 on 2025-06-16 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='visit',
        ),
        migrations.AlterField(
            model_name='report',
            name='analysis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='analysis.analysis'),
        ),
        migrations.AlterField(
            model_name='report',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_visit', to='visits.visit'),
        ),
    ]
