# Generated by Django 5.1.3 on 2025-05-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=254)),
                ('Work_start_time', models.TimeField()),
                ('Work_end_time', models.TimeField()),
            ],
        ),
    ]
