# Generated by Django 5.1.3 on 2025-06-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='clinic',
        ),
    ]
