# Generated by Django 5.1.3 on 2025-06-26 06:14

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_column='Phone_number', max_length=128, region=None, unique=True),
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Phone_number',
            new_name='_Phone_number',
        ),
    ]
